### ISSUE TITLE
run euroc dataset in lsd-slam

### ISSUE THREAD

**Issue by pisuto** [shidahe/semidense-lines#10]
Hi,

when I wanted to repeat your experiment running euroc dataset room V101 and V201 in lsd-slam to get relative point clouds, I met tracking lost and couldn't get the same points as yours. I guess the camera calibration is the problem. 

below it's my camera calibration for euroc room dataset:
`0.608493 0.950279 0.505318 0.531746 0
752 480
none
752 480`

the point cloud of euroc room v101(I cannot recognize what it is...):
![1](https://user-images.githubusercontent.com/24860995/52558465-6b4b1700-2e2d-11e9-8e2d-c232e29ac4f9.png)

So, do you have any idea? Do you change any code in lsd-slam or could you show your calibration file?
Thank you very much!

**Comment by shidahe** [comment]
Thanks for being interested in the project!

For my master's thesis, I remember I did change some code in LSD-SLAM to produce a meaningful point cloud. This repo is only about ORB-SLAM though. 

The code I had for LSD-SLAM is buried somewhere is my old hard-drive, so I am not exactly sure what I did. But I remember it is something simple, like filtering out the points that are too far from camera.

For calibration file, maybe try this one: https://github.com/tum-vision/LDSO/blob/master/examples/EUROC/EUROC.txt 
This should be the calibration that they use in their recent project, and I assume their calibration format didn't change too much.

**Comment by shidahe** [comment]
Oh sorry I notice that their calibration format did change from DSO. So the one above may not work as is.

I am not likely to find my old callibration file in a short amount of time, so I am afraid I can't really help much on this. Maybe try a different camera model for the calibration file and use something other than 'none'.

**Comment by pisuto** [comment]
Okay, thank you very much!
I think you give me a useful clue.
Thank you again!

**Comment by pisuto** [comment]
below it's what I want.
`0.6099122 0.95061667 0.4883178 0.51722791 -0.28340811 0.07395907 0.00019359 1.76187114e-05

752 480

crop

640 480`

Thank you again.
