### ISSUE TITLE
linking issue on ubuntu 14

### ISSUE THREAD

**Issue by kerautret** [shidahe/semidense-lines#3]
I have an error when applying the compilation script build.sh:

```
[  2%] Linking CXX shared library ../lib/libORB_SLAM2.so
/usr/bin/ld : architecture i386:x86-64 du fichier d'entrée « ../Thirdparty/EDLines/EDLinesLib.a(ED.o) » est incompatible avec la sortie i386

```

**Comment by shidahe** [comment]
It looks like a 32bit/64bit compatibility issue. The included EdgeDrawing and EDLines executable are 64bit. If you are building on a 32bit system, you may try downloading the 32bit version of [EdgeDrawing] (http://ceng.anadolu.edu.tr/CV/EdgeDrawing/) and [EDLines](http://ceng.anadolu.edu.tr/cv/EDLines/).

**Comment by kerautret** [comment]
👍thanks that fix the pb perhaps you can mention it in the readme.
Now the compilation is done from my ubuntu ;)

**Comment by shidahe** [comment]
Issue fixed
